lightning_trainer:
  _target_: lightning.pytorch.trainer.trainer.Trainer
  _partial_: True
  check_val_every_n_epoch: null
  val_check_interval: 200
  max_steps: 5000
  max_epochs: -1
  accelerator: gpu
  devices: 4
  strategy: "ddp"
  precision: 16-mixed
  log_every_n_steps: 10

lightning_module:
  _target_: modules.segmentation.TrainModule
  _partial_: True
  prediction_threshold: 0.5

  loss:
    _target_: monai.losses.DiceFocalLoss
    sigmoid: True
    reduction: "mean"
    squared_pred: True
    gamma: 2.0
    lambda_focal: 0.5
    lambda_dice: 0.5

  optimizer_factory:
    _target_: torch.optim.AdamW
    _partial_: True
    lr: ${lr}
    weight_decay: 0.0001
    betas: [0.9, 0.999]

  scheduler_configs:
    linear_warmup:
      interval: step
      frequency: 10
      scheduler:
        _target_: torch.optim.lr_scheduler.LinearLR
        _partial_: True
        start_factor: 0.01
        end_factor: 1.0
        total_iters: 10
    cosine_annealing:
      interval: step
      frequency: 10
      scheduler:
        _target_: torch.optim.lr_scheduler.CosineAnnealingLR
        _partial_: True
        T_max: 490
        eta_min: 0.000001
        last_epoch: -1